@startuml login

skinparam dpi 300
skinparam ActorFontSize 20
skinparam UsecaseFontSize 20
skinparam ParticipantPadding 70
skinparam sequenceMessageAlign center


actor Customer as c
participant CLup as sys
participant "SMS Third Party" as sms

c -> sys ++ : sendPhoneNumber
sys -> sms ++ : sendSMSWithToken

loop Until token received
    alt Missed token
        c -> sys : askNewToken
        sys -> sms : sendSMSWithToken
    else Token received
        return token
        c -> sys : sendToken
        alt The token is valid
            sys --> c : success
        else Invalid token, restart
            return error
        end
    end
end

@enduml