@startuml reserve timeslot
skinparam dpi 300
skinparam ActorFontSize 15
skinparam UsecaseFontSize 12
scale 1000 width

actor Customer as c
participant CLup as sys

c -> sys ++ : retrieveStoreList
return storeList

c -> sys ++ : selectStore
return storeDetails

c -> sys ++ : retrieveAvailableTimeSlots
return timeSlots

c -> sys ++ : reserveTimeSlot
return reservationReceipt

@enduml