@startuml
left to right direction
Manager as m
User as u
"Authenticated User" as au
"Totem User" as tu
rectangle {
    m -- (Modify\nStores)
    m -- (Check\nStore)

    (Modify\nStores) <-[dashed]- (Add\nStore) : <<extends>>
    (Modify\nStores) <-[dashed]- (Edit\nStore) : <<extends>>
    (Edit\nStore) <-[dashed]- (Change\nCapacity) : <<extends>>
    (Edit\nStore) <-[dashed]- (Change\nTime Slots) : <<extends>>

    u -- (Login)

    au -- (Check\nStatus)
    au -- (Select\nStore)
    (Check\nStatus) <-[dashed]- (Leave\nQueue) : <<extends>>
    (Check\nStatus) <-[dashed]- (Cancel\nReservation) : <<extends>>
    (Select\nStore) <-[dashed]- (Book) : <<extends>>
    (Select\nStore) <-[dashed]- (Join\nQueue) : <<extends>>

    tu -- (Join\nQueue)
    



}
@enduml