@startuml

skinparam dpi 300
skinparam ActorFontSize 20
skinparam UsecaseFontSize 15

left to right direction


Manager as m
User as u
"Authenticated User" as au
"Totem User" as tu
rectangle {
    m -- (Modify\nStores)
    m -- (Check\nStore)

    (Modify\nStores) <-[dashed]- (Add\nStore) : <<extends>>
    (Modify\nStores) <-[dashed]- (Edit\nStore) : <<extends>>

    u -- (Login)

    (Book) -- au 
    (Join\nLine) -- au 
    (Leave\nLine) -- au 
    (Cancel\nReservation) -- au
    (Select\nStore) <-[dashed]- (Book)  : <<includes>>
    (Select\nStore) <-[dashed]- (Join\nLine)  : <<includes>>

    (Add\nStore) -[hidden]- (Select\nStore)
    (Select\nStore) -[hidden]- (Leave\nLine)
    (Select\nStore) -[hidden]- (Cancel\nReservation)

    tu -- (Join\nLocal\nLine)
    



}

@enduml