@startuml
left to right direction
User as u
"Authenticated User" as au
Manager as m
' Totem as t
rectangle {
    u -- (Login)
    u -- (Check\nStatus)
    u -- (Join\nQueue)

    au -- (Join\nQueue)
    au -- (Book)
    au -- (Check\nStatus)

    (Join\nQueue) -- (Find\nStore) : <<includes>>
    (Book) -- (Find\nStore) : <<includes>>

    m -- (Modify\nStores)
    (Modify\nStores) -- (Add\nStore) : <<extends>>
    (Modify\nStores) -- (Edit\nStore) : <<extends>>
    (Edit\nStore) -- (Change\nCapacity) : <<extends>>
    (Edit\nStore) -- (Change\nTime Slots) : <<extends>>
    m -- (Check\nStore)
}
@enduml