@startuml visit_state_diagram
hide empty description
skinparam dpi 300
skinparam ActorFontSize 15
skinparam UsecaseFontSize 12

state end1 <<end>>

[*] -> visit_active : create_booking

visit_active -> visit_delayed : problem_occurs
visit_active --> visit_cancelled : user_abort
visit_active --> visit_cancelled : user_late
visit_active -> visit_done : qr_code_scanned

visit_delayed --> visit_cancelled : user_abort
visit_delayed -> visit_done : qr_code_scanned

visit_done --> end1
visit_cancelled --> [*]

@enduml