@startuml seq_join_queue_totem


skinparam {
   dpi 300
}

actor Totem as a
participant QueueManager as queue
participant QueryManager as qm
database DBMS as db

a -> queue : joinQueue(storeId)
activate queue
queue -> qm : addTotemUserToQueue(storeId, receiptId)
activate qm
qm -> db : addTotemUserToQueue(storeId, receiptId)
db --> qm : <OK>
qm --> queue : <OK>
deactivate qm
queue --> a : Receipt
deactivate queue

@enduml