@startuml seq_user_login

skinparam {
   dpi 300
}

actor User as a
participant Account_Manager as am
participant SMS_API as sms
participant Query_Manager as qm
database DBMS as db

a -> a : Input phone number
a -> am : loginWithPhoneNumber(phoneNum)
activate am
am -> sms : sendVerificationCode (phoneNum,code)
activate sms
sms --> a : Send SMS with code
deactivate sms
a -> a : Input received SMS code
a -> am : verifyPhoneNumber(phoneNum, code)
am -> qm : checkIfPhoneNumberIsPresent (phoneNum)
activate qm
qm -> db : queryUser (phoneNum)

alt user already registered
    db --> qm : user tuple
    qm --> am : user data
    ||| 
else user not registered
    db --> qm : No match found!
    qm -> am : Phone number not taken!
    am -> qm : createUser(phoneNum)
    activate qm
    qm -> db : createUser(phoneNum)
    db --> qm : <OK>
    qm --> am : <OK>
    deactivate qm
end
    am -> qm : createUserToken(phoneNum)
    activate qm
    qm -> db : createUserToken(phoneNum, token)
    db --> qm : <OK>
    qm --> am : <OK>
    deactivate qm
    am --> a : <OK> user token
    deactivate am
@enduml