@startuml seq_join_queue

actor User as a
participant StoreSearch as ss
participant ReservationManager as rm
participant QueueManager as queue
participant QueryManager as qm
database DBMS as db

a -> ss : getStores (currentLocation, [filters])
activate ss 
ss -> qm : getStoreIds (location, [filters])
activate qm
qm -> db : queryStores(location, [filters])

alt No Store matching query
    db --> qm : No stores found!
    qm --> ss : No stores found!
    ss --> a  : <ALERT> No store found!
    |||
else Stores found
    db --> qm : List of store IDs
    qm --> ss : List of store IDs
    deactivate qm
    ss --> a : <OK>  List of store IDs
    deactivate ss
    |||
    loop for all the IDs received
        a->rm : getReservationData(storeID)
        activate rm
        rm -> qm : getReservationDataByStoreId(storeID)
        activate qm
        qm -> db : queryStoreReservations(storeID)
        db --> qm : List of timeslots
        qm --> rm : Reservation data of storeID
        deactivate qm
        rm --> a : <OK> Reservation data of storeID
        deactivate rm
        |||
        a-> queue : getQueueData(storeID)
        activate queue
        queue -> qm : getQueueDataByStore(storeID)
        activate qm
        qm -> db : queryStoreQueue(storeID)
        db --> qm : Queue status
        qm --> queue : Queue data of storeID
        deactivate qm
        queue --> a : <OK> Queue data of storeID
        deactivate queue
        |||
    end
    |||
end

@enduml